apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xlzt8zuy7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xlzt8zuy7-python 
  name: xlzt8zuy7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xlzt8zuy7-python 
